# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-05 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clientname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
